sudo: required
services:
  - docker
before_install:
  - docker build -t sbellale/docker-react -f Dockerfile.dev .

script:
  - docker run sbellale/docker-react npm run test -- --coverage --watchAll=false
